# Generated by Django 5.2.1 on 2025-05-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=40)),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_Joining', models.DateField()),
                ('emp_dep', models.CharField(max_length=40)),
                ('emp_password', models.IntegerField()),
            ],
        ),
    ]
