# Generated by Django 5.2.1 on 2025-05-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_employee_emp_age_employee_emp_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
