# Generated by Django 5.2.1 on 2025-05-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_employee_emp_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='image/'),
        ),
    ]
